# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:carbon
LABEL MAINTAINER "Subash SN"

WORKDIR /appdsdsd

RUN npm install -g nodemon

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
